#!/bin/bash
#
# ANSI color codes cheat sheet
#

title() {
    echo -e "\n\033[1m$1\033[0m"
}

palette_16() {
    local text='gYw'
    local fg_name
    local fg_spec
    local bg_spec

    echo -e "\n                 40m     41m     42m     43m     44m     45m     46m     47m"
    for fg_name in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' '  36m' '1;36m' '  37m' '1;37m'; do
        fg_spec=${fg_name// /}
        echo -en " $fg_name \033[$fg_spec  $text  "
        for bg_spec in 40m 41m 42m 43m 44m 45m 46m 47m; do
            echo -en " \033[$fg_spec\033[$bg_spec  $text \033[0m\033[$bg_spec \033[0m"
        done
        echo
    done

    echo
}

palette_256() {
    local prefix="$1"
    local text="$2"

    local i
    local j
    local value

    echo -en "\n   +  "
    for i in {0..35}; do
        printf "%2b " $i
    done

    printf "\n\n %3b  " 0
    for i in {0..15}; do
        echo -en "\033[${prefix}${i}m${text}\033[m "
    done

    for i in {0..6}; do
        ((i = i * 36 + 16))
        printf "\n\n %3b  " $i
        for j in {0..35}; do
            ((value = i + j))
            echo -en "\033[${prefix}${value}m${text}\033[m "
        done
    done

    echo -e "\n"
}

title "ANSI color codes cheat sheet"
echo '
Color is set using \033[${value}m control characters where ${value} can be
a valid set of semicolon separated numbers:

For 16 color palette:
* Font colors: 30-37
* Background colors: 40-47
For example: \033[37;41m

For 256 color palette:
* Font color is prepended with 38;5;
* Background color is prepended with 48;5;
For example: \033[38;5;196;48;5;21m

There are additional specifiers that may be prepended to color specification:
* 0 (or no value given) for the font color resets it to the default, which depends on the setup
* 1 sets the font to bright/bold
* 4 sets it to underlined
* 7 sets it to negative colors
For example: \033[1;37;41m
'

title "16 color palette:"
palette_16

title "256 color font palette:"
palette_256 '38;5;' 'XX'

title "256 color bold/bright font palette:"
palette_256 '1;38;5;' 'XX'

title "256 color background palette:"
palette_256 '48;5;' '  '
